const works = [
  {
    name: 'Fast Land Racers',
    description: 'Fast-Lane-Racer is a car booking website that allows users to easily book a ride and travel to their desired destinations. User can reserve a car from the available cars by providing the date and city. Provides a seamless and reliable car booking experience.',
    smalldesc: 'Is a car booking website that allows users to easily book a ride and travel to their desired destinations.',
    image: 'image/mock-racer.webp',
    technologies: ['html', 'Ruby on rails', 'css', 'JavaScript', 'PostgreSQL', 'React', 'Redux'],
    linkLive: 'https://shiny-longma-bba6fb.netlify.app',
    linkCode: 'https://github.com/LarryIVC/Fast-Lane-Racers-front-end',
    enterprise: 'Microverse',
    stack: 'Front End & Back End Dev',
    year: '2023',
  },
  {
    name: 'Pennywise',
    description: 'Pennywise: Manage your finances with ease. Track spending, set budgets, gain insights, and make informed decisions for financial freedom. Start today!',
    smalldesc: 'Manage your finances with ease, spendigs and budgets',
    image: 'image/pennywise.webp',
    technologies: ['erb', 'CSS', 'JavaScript', 'Ruby', 'Ruby on rails', 'PostgreSQL'],
    linkLive: 'https://rails-lb6q.onrender.com/',
    linkCode: 'https://github.com/LarryIVC/pennywise',
    enterprise: 'Microverse',
    stack: 'Back End Dev',
    year: '2023',
  },
  {
    name: 'Crypto Coinranking',
    description: 'Is a powerful web application designed specifically for crypto coins. It leverages the capabilities of React and Redux to provide comprehensive information about various cryptocurrencies.',
    smalldesc: 'Is a powerful web application designed specifically for crypto coins.',
    image: 'image/cryptomock.png',
    technologies: ['html', 'css', 'JavaScript', 'React', 'Redux'],
    linkLive: 'https://react-coin-coinranking.netlify.app/',
    linkCode: 'https://github.com/LarryIVC/react-coins',
    enterprise: 'Microverse',
    stack: 'Front End Dev',
    year: '2023',
  },
  {
    name: 'The Simpsons Fans Club',
    description: 'This project demonstrates my ability to use JavaScript, Webpack, and Jest, as well as reading and writing APIs using JSON.',
    smalldesc: 'This project demonstrates my ability to use JavaScript, Webpack, and Jest, as well as reading and writing APIs using JSON.',
    image: 'image/simpmock.jpeg',
    technologies: ['html', 'css', 'JavaScript'],
    linkLive: 'https://js-capstoneproject.netlify.app/',
    linkCode: 'https://github.com/LarryIVC/portfolio',
    enterprise: 'Microverse',
    stack: 'Front End Dev',
    year: '2023',
  },
  {
    name: 'Catholic Music Concert',
    description: 'Landing page specifically to promote a Catholic concert. The design is intuitive and easy to use, allowing visitors to quickly and easily access all the essential details about the concert, including the date, time, venue, and artists.',
    smalldesc: 'Landing page specifically to promote a Catholic concert.',
    image: 'image/event.webp',
    technologies: ['html', 'css', 'JavaScript'],
    linkLive: 'https://larryivc.github.io/EventPage/',
    linkCode: 'https://github.com/LarryIVC/EventPage',
    enterprise: 'Microverse',
    stack: 'Front End Dev',
    year: '2023',
  },
];

export default works;