const works = [
  {
    name: 'Fast Land Racers',
    description: 'Fast-Lane-Racer is a car booking website that enables users to effortlessly book rides and travel to their desired destinations. Users can reserve a car from the available options by providing the date and city, ensuring a seamless and reliable car booking experience.',
    smalldesc: 'It\'s a car booking website that enables users to effortlessly book rides and travel to their desired destinations.',
    image: 'image/mock-racer.webp',
    technologies: ['html', 'Ruby on rails', 'css', 'JavaScript', 'PostgreSQL', 'React', 'Redux'],
    linkLive: 'https://shiny-longma-bba6fb.netlify.app',
    linkCode: 'https://github.com/LarryIVC/Fast-Lane-Racers-front-end',
    enterprise: 'Microverse',
    stack: 'Front & Back End Dev',
    year: '2023',
  },
  {
    name: 'Pennywise',
    description: 'Pennywise: Simplify your finances. Track expenses, set budgets, gain insights, and make informed decisions for financial freedom. Get started today!',
    smalldesc: 'Manage your finances with ease: expenses and budgets.',
    image: 'image/pennywise.webp',
    technologies: ['erb', 'CSS', 'JavaScript', 'Ruby', 'Ruby on rails', 'PostgreSQL'],
    linkLive: 'https://rails-lb6q.onrender.com/',
    linkCode: 'https://github.com/LarryIVC/pennywise',
    enterprise: 'Microverse',
    stack: 'Back End Dev',
    year: '2023',
  },
  {
    name: 'Crypto Coinranking',
    description: 'It\'s a powerful web application designed specifically for cryptocurrencies. Leveraging the capabilities of React and Redux, it offers comprehensive information about various digital coins.',
    smalldesc: 'It\'s a powerful web application designed specifically for cryptocurrencies.',
    image: 'image/cryptomock.png',
    technologies: ['html', 'css', 'JavaScript', 'React', 'Redux'],
    linkLive: 'https://react-coin-coinranking.netlify.app/',
    linkCode: 'https://github.com/LarryIVC/react-coins',
    enterprise: 'Microverse',
    stack: 'Front End Dev',
    year: '2023',
  },
  {
    name: 'The Simpsons Fans Club',
    description: 'This project showcases my proficiency in JavaScript, Webpack, and Jest, along with my skills in working with JSON for reading and writing APIs.',
    smalldesc: 'This project showcases my proficiency in JavaScript, Webpack, and Jest, as well as my capability in working with JSON for reading and writing APIs.',
    image: 'image/simpmock.jpeg',
    technologies: ['html', 'css', 'JavaScript'],
    linkLive: 'https://js-capstoneproject.netlify.app/',
    linkCode: 'https://github.com/LarryIVC/portfolio',
    enterprise: 'Microverse',
    stack: 'Front End Dev',
    year: '2023',
  },
  {
    name: 'Catholic Music Concert',
    description: 'A landing page specifically created to promote a Catholic concert. The design is intuitive and user-friendly, enabling visitors to access essential concert details such as date, time, venue, and artists quickly and easily.',
    smalldesc: 'A landing page designed exclusively for the promotion of a Catholic concert.',
    image: 'image/event.webp',
    technologies: ['html', 'css', 'JavaScript'],
    linkLive: 'https://larryivc.github.io/EventPage/',
    linkCode: 'https://github.com/LarryIVC/EventPage',
    enterprise: 'Microverse',
    stack: 'Front End Dev',
    year: '2023',
  },
];

export default works;