const works = [
  {
    name: 'Pennywise',
    description: 'Pennywise: Manage your finances with ease. Track spending, set budgets, gain insights, and make informed decisions for financial freedom. Start today!',
    smalldesc: 'Manage your finances with ease, spendigs and budgets',
    image: 'image/pennywise.webp',
    technologies: ['erb', 'CSS', 'JavaScript', 'Ruby', 'Ruby on rails', 'PostgreSQL'],
    linkLive: 'https://rails-lb6q.onrender.com/',
    linkCode: 'https://github.com/LarryIVC/pennywise',
    canopy: 'Back End Dev',
    year: '2023',
  },
  {
    name: 'Fast Land Racers',
    description: 'Fast-Lane-Racer is a car booking website that allows users to easily book a ride and travel to their desired destinations. User can reserve a car from the available cars by providing the date and city. Fast-Lane-Racer provides a seamless and reliable car booking experience.',
    smalldesc: 'Is a car booking website that allows users to easily book a ride and travel to their desired destinations.',
    image: 'image/mock-racer.webp',
    technologies: ['html', 'Ruby on rails', 'css', 'JavaScript', 'PostgreSQL', 'React', 'Redux'],
    linkLive: 'https://shiny-longma-bba6fb.netlify.app',
    linkCode: 'https://github.com/LarryIVC/Fast-Lane-Racers-front-end',
    canopy: 'Front End & Back End Dev',
    year: '2023',
  },
  {
    name: 'Crypto Coinranking',
    description: 'Is a powerful web application designed specifically for crypto coins. It leverages the capabilities of React and Redux to provide comprehensive information about various cryptocurrencies.',
    smalldesc: 'Is a powerful web application designed specifically for crypto coins.',
    image: 'image/cryptomock.png',
    technologies: ['html', 'css', 'JavaScript', 'React', 'Redux'],
    linkLive: 'https://react-coin-coinranking.netlify.app/',
    linkCode: 'https://github.com/LarryIVC/react-coins',
    canopy: 'Front End Dev',
    year: '2023',
  },
  {
    name: 'The Simpsons Fans Club',
    description: 'This project demonstrates my ability to use JavaScript, Webpack, and Jest, as well as reading and writing APIs using JSON.',
    smalldesc: 'This project demonstrates my ability to use JavaScript, Webpack, and Jest, as well as reading and writing APIs using JSON.',
    image: 'image/simpmock.jpeg',
    technologies: ['html', 'css', 'JavaScript'],
    linkLive: 'https://js-capstoneproject.netlify.app/',
    linkCode: 'https://github.com/LarryIVC/portfolio',
    canopy: 'Front End Dev',
    year: '2023',
  },
];

export default works;